In [5]:
import torch
import numpy as np

# create a tensor on the gpu
device = torch.device("cuda")

In [6]:
x = torch.ones(5 ,dtype=torch.float64, device=device)
print(x)

tensor([1., 1., 1., 1., 1.], device='cuda:0', dtype=torch.float64)


In [7]:
y = torch.tensor([1,1,1,1,1])
y = y.to(device)
print(y)

tensor([1, 1, 1, 1, 1], device='cuda:0')


In [8]:
z = x + y
z = z.to("cpu")
z_np = z.numpy()
z_tr = torch.from_numpy(z_np) # by reference
print(z_np)
print(z_tr)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
